name: Checkout with ref

on: [push]

jobs:
  proper-work:
    name: Proper Work
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/heads/main'
      - uses: actions/setup-node@v2
      - run: node ./index.js


